# Generated by Django 5.2.14 on 2026-05-08 20:57

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
