# Generated by Django 5.2.14 on 2026-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_payment_status'),
        ('users', '0002_alter_patient_full_name_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'timeslot'), name='uniq_doctor_date_timeslot'),
        ),
    ]
